# fly.toml app configuration file generated for johnandmaritza on 2026-02-17T12:16:12-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'johnandmaritza'
primary_region = 'dfw'
swap_size_mb = 2048

[build]
  image = 'johnandmaritza:latest'

[http_service]
  internal_port = 3000
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 0

  [http_service.http_options]
    h2_backend = true

[[vm]]
  size = 'shared-cpu-1x'
